### ISSUE TITLE
English (UK) dictionary is full of abbreviations

### ISSUE THREAD

**Issue by DestyNova** [lexica/lexica#87] opened 2018-06-01 14:56 UTC
The word counts are somewhat misleading due to the many abbreviations (like FTP and STD). It might be nice to remove these, although only if there isn't a real word with the same letters (CAT).

**Comment by pserwylo** [comment] 2018-06-01 23:13
Thanks for the report @DestyNova. I hope that this will be fixed when #58 is implemented (higher quality English dictionary). I'll close this as a duplicate of that for now.

**Closed by pserwylo** 2018-06-01 23:13 UTC
