### ISSUE TITLE
Allow user to change UI language

### ISSUE THREAD

**Issue by RustanHakansson** [lexica/lexica#176] opened 2020-09-03 05:41 UTC
I fixed some translations to Swedish UI that were hard to understand. But one was so weird that I do not know what it was meant to say, so wanted to switch to English in game to know what it did. But there is no way to do that as far as I can find.

**Comment by pserwylo** [comment] 2020-09-03 06:01
Closing as a duplicate of #148. Thanks for updating the translations!

**Closed by pserwylo** 2020-09-03 06:01 UTC

**Comment by RustanHakansson** [comment] 2020-09-03 06:18
Oops, sorry. Searched a while in the issues but did not find that one.
