### ISSUE TITLE
Non-English words expected in English-language game, while actual English words not accepted

### ISSUE THREAD

**Issue by xander-page** [lexica/lexica#265] opened 2021-08-05 12:21 UTC
I've noticed a lot of weirdness in what Lexica considers to be a word and what it doesn't. For example, it thinks [nae](https://en.wiktionary.org/wiki/nae) and [frin](https://en.wiktionary.org/wiki/frin) are words. In fact, I've found that quite a lot of Scots words (or at least words in use on the Scots Wikipedia, which doesn't necessarily mean they _are_ Scots words) get accepted.

But meanwhile, words that are actually in active use in _English_ don't get accepted. I've been compiling a list.

## Loanwords
* [zen](https://en.wiktionary.org/wiki/zen)
* [eid](https://en.wiktionary.org/wiki/Eid)
* [ube](https://en.wiktionary.org/wiki/ube)

## STEM words
* [bio](https://en.wiktionary.org/wiki/bio)
* [bot](https://en.wiktionary.org/wiki/bot)
* [brane](https://en.wiktionary.org/wiki/brane)
* [dopant](https://en.wiktionary.org/wiki/dopant)
* [reals](https://en.wiktionary.org/wiki/reals)
* [valent](https://en.wiktionary.org/wiki/valent)

## ??? words (the omission of these is baffling)
* [boing](https://en.wiktionary.org/wiki/boing)
* [bro](https://en.wiktionary.org/wiki/bro)
* [eval](https://en.wiktionary.org/wiki/eval)
* [lede](https://en.wiktionary.org/wiki/lede) (may have originated falsely, but is in regular usage, which is what I dare say makes a word "a word")
* [niner](https://en.wiktionary.org/wiki/niner)
* [outie](https://en.wiktionary.org/wiki/outie)
* [pads](https://en.wiktionary.org/wiki/pads) (literally why not?????)
* [raws](https://en.wiktionary.org/wiki/raws)
* [stat](https://en.wiktionary.org/wiki/stat)
* [stoner](https://en.wiktionary.org/wiki/stoner)
* [trans](https://en.wiktionary.org/wiki/trans) (although [cis](https://en.wiktionary.org/wiki/cis) is accepted when I would have expected it to be the other way around)
* [vape](https://en.wiktionary.org/wiki/vape)

Some of these were collected while using an earlier version, since I'm sure you can appreciate the difficulty in reproducing the errors. But every time I re-check a word that is on this list, it hasn't changed, so...

**Comment by davidpiano** [comment] 2021-12-01 07:18
I agree it would be nice to include these. It appears to me that the reason *most* of your words were omitted is that whoever was compiling the list either considered them too jargon-y or simply didn't think of them. A few of them are, as you said, baffling - but I'd suggest there might not be as many baffling ones as you thought, and more that can be attributed to infrequent updates or to maintainers who don't read all the same things you do. Notwithstanding all that, any dictionary that doesn't include "boing" is mystifying. :)

**Comment by pserwylo** [comment] 2021-12-01 09:38
Hi all. For some context, this game was forked from Lexic - a game made over 10 years ago. Although it was GPL licensed, the origin of the dictionaries used is unknown. One thing I'd really like to do is to choose a well supported English dictionary from a known source, with an appropriate license, and use that. Hopefully one that is able to accept pull requests for missing words so that this little Lexica project doesn't have the burden of maintaining multiple different language dictionaries. There is indeed some discussion about this that has been started some time ago, I just haven't gotten around to actioning it (see #58 and #180).

For now, I will close this ticket as a duplicate of these others, but I really do appreciate you collecting this list of words. 

For what it is worth, you can find the source dictionary containing every word that Lexica thinks is a word here: https://github.com/lexica/lexica/tree/master/assets/dictionaries

**Closed by pserwylo** 2021-12-01 09:38 UTC
