### ISSUE TITLE
Complete crash of the game when clicking "new game"

### ISSUE THREAD

**Issue by Porkepix** [lexica/lexica#64] opened 2018-04-25 06:44 UTC
When clicking new game, using version 0.11 from F-droid, the game is just completely crashing.

Here's the result of adb `logcat -v threadtime` when it crashes:

```
04-25 08:42:55.936 23150 23150 D Game    : Language (from preferences): en_US
04-25 08:42:55.940 23150 23150 W ResourceType: No package identifier when getting value for resource number 0x00000000
04-25 08:42:55.941 23150 23150 E PlayLexica: top level
04-25 08:42:55.941 23150 23150 E PlayLexica: android.content.res.Resources$NotFoundException: Resource ID #0x0
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at android.content.res.Resources.getValue(Resources.java:1358)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at android.content.res.Resources.openRawResource(Resources.java:1272)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at android.content.res.Resources.openRawResource(Resources.java:1248)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at com.serwylo.lexica.a.e.a(Unknown Source)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at com.serwylo.lexica.a.e.c(Unknown Source)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at com.serwylo.lexica.a.e.a(Unknown Source)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at com.serwylo.lexica.a.e.<init>(Unknown Source)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at com.serwylo.lexica.PlayLexica.k(Unknown Source)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at com.serwylo.lexica.PlayLexica.onCreate(Unknown Source)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at android.app.Activity.performCreate(Activity.java:6285)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at android.os.Looper.loop(Looper.java:234)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at java.lang.reflect.Method.invoke(Native Method)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-25 08:42:55.941 23150 23150 E PlayLexica: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-25 08:42:55.961 23150 23150 D Game    : Language (from preferences): en_US
04-25 08:42:55.962 23150 23150 W ResourceType: No package identifier when getting value for resource number 0x00000000
04-25 08:42:55.962 23150 23150 D AndroidRuntime: Shutting down VM
04-25 08:42:55.962 23150 23150 E AndroidRuntime: FATAL EXCEPTION: main
04-25 08:42:55.962 23150 23150 E AndroidRuntime: Process: com.serwylo.lexica, PID: 23150
04-25 08:42:55.962 23150 23150 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.serwylo.lexica/com.serwylo.lexica.PlayLexica}: android.content.res.Resources$NotFoundException: Resource ID #0x0
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3160)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3191)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2529)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:234)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at android.content.res.Resources.getValue(Resources.java:1358)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at android.content.res.Resources.openRawResource(Resources.java:1272)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at android.content.res.Resources.openRawResource(Resources.java:1248)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at com.serwylo.lexica.a.e.a(Unknown Source)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at com.serwylo.lexica.a.e.c(Unknown Source)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at com.serwylo.lexica.a.e.a(Unknown Source)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at com.serwylo.lexica.a.e.<init>(Unknown Source)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at com.serwylo.lexica.PlayLexica.k(Unknown Source)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at com.serwylo.lexica.PlayLexica.onResume(Unknown Source)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6361)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3149)
04-25 08:42:55.962 23150 23150 E AndroidRuntime: 	... 10 more
```

EDIT: Running on an Android 6.0.1 phone with standard Sony ROM.

**Comment by pserwylo** [comment] 2018-04-25 11:28
Arg! Thanks for letting me know. This is caused by the fact that Proguard is being overzelous in removing my dictionaries from the code. This is because they are referenced dynamically, rather than explicitly. 

I have a fix on the way, and will push a new version tonight - to be released on F-Droid ASAP.

**Comment by pserwylo** [comment] 2018-04-25 21:28
Going to reopen this until it is released on F-Droid. Also, for prosterity, it wasn't that Proguard was removing the dictionary files, but rather that they were never getting built in the first place! Version 0.11.1 updates the build script to ensure that they are built. It also removes Proguard just in case that was going to subsequently remove the files anyway.

**Comment by cengizIO** [comment] 2018-04-26 13:49
@pserwylo thanks for fixing this. Might be offtopic but how can we speedup F-Droid release? Is it polling this artifact to monitor changes?

**Comment by Porkepix** [comment] 2018-04-26 15:03
It's sadly a little bit more complicated.
As far as I know, if the application is correctly registered on F-droid's side, then it's watching over new tags for new versions and automatically building new ones. However one of the lasts steps is a manual one (signing if I'm not wrong), and same goes from new repository indexes.
And I've no idea how this could really be improved, F-droid team is very small.

**Comment by hhassey** [comment] 2018-04-27 22:39
I just want to report that I have the same problem on Samsung Galaxy S6, It seems that you have tackled this bug, And I have been visiting F-Droid in the hopes to get the update!.
Thanks for the work

**Comment by Bubu** [comment] 2018-04-28 20:03
Released and fixed on F-Droid.

(Hey Peter, didn't know you were behind this app :))

**Closed** 2018-04-30 10:47 UTC
