### ISSUE TITLE
In french accents and special char should not count

### ISSUE THREAD

**Issue by sycom** [lexica/lexica#126] opened 2019-11-28 07:40 UTC
In most word games in french é è ç and so on are considered as e c...
It would enhance game combinations a lot.

**Comment by gitbaud** [comment] 2020-04-13 09:33
I agree, it would be great without accents and special char.

**Comment by rffontenelle** [comment] 2020-05-16 19:32
Duplicate of #71 ?

**Comment by imariasantos** [comment] 2020-12-17 18:52
This is how crossword puzzles work in French: diacritics are ignored. It would make more sense for this game to also ignore diacritics.

**Comment by imariasantos** [comment] 2020-12-17 19:43
> Duplicate of #71 ?

The issue with distinguishing "a" from "â" is the same as the problem raised in issue #107. But this issue is not quite a duplicate. 
For instance, "é" is a letter recognized by French speaking people, and it is not pronounced the same as "e". However, not distinguishing the two in word games makes these games much more playable.

**Comment by pserwylo** [comment] 2021-03-21 06:50
Can I please get some feedback from any native French speakers? I have a version ready to release which includes two french dictionaries:

* French (Extended) - Includes diacritics: àâçéèêëîïôöûü
* French

The extended version uses the same dictionary as the current French dictionary in Lexica (but will be renamed to "French (Extended)". It will also include the description "Includes diacritics: àâçéèêëîïôöûü" alongside the language name when choosing which language to play with.

The new dictionary will just be called "French" and will not have any description next to it. It will only have ASCII characters in it, so no diacritics at all.

**Does this sound reasonable?**

For those technically minded, this is the script used to remove such characters (from [here](https://stackoverflow.com/a/10207623)):

> `iconv -f utf8 -t ascii//TRANSLIT "$INPUT_DICT_FILE" | sort | uniq > "$OUTPUT_DICT_FILE"`

**Comment by gitbaud** [comment] 2021-03-21 14:36
> Can I please get some feedback from any native French speakers? I have a version ready to release which includes two french dictionaries:
> 
> * French (Extended) - Includes diacritics: àâçéèêëîïôöûü
> * French
> 
> The extended version uses the same dictionary as the current French dictionary in Lexica (but will be renamed to "French (Extended)". It will also include the description "Includes diacritics: àâçéèêëîïôöûü" alongside the language name when choosing which language to play with.
> 
> The new dictionary will just be called "French" and will not have any description next to it. It will only have ASCII characters in it, so no diacritics at all.
> 
> **Does this sound reasonable?**
> 

yes, this sounds great, thank-you !

**Comment by pserwylo** [comment] 2021-03-21 20:25
Thank you so much for the quick feedback. I'll post back here when releasing the new version so that you can test and provide feedback.

**Comment by pserwylo** [comment] 2021-03-27 03:38
Okay, here we go: [v2.1.0 has been tagged](https://github.com/lexica/lexica/releases/tag/v2.1.0) ready to be built by F-Droid. It includes both dictionaries as discussed in this thread. It doesn't include Weblate translations yet, but as they role in, I'll bump minor releases to include them (as they will have translations for these new dictionary descriptions) - just keen to get feedback on the actual dictionaries. Thanks again for all your input, this really wouldn't be such an international game withotu input from those in the community helping to ensure their language is supported.

**Closed by pserwylo** 2021-03-27 03:38 UTC
Labels: dictionaries
