### ISSUE TITLE
Lexica app gets crashed.

### ISSUE THREAD

**Issue by Sammaz2** [lexica/lexica#85] opened 2018-05-23 17:37 UTC
### Actual behavior
I opened the lexica opensource android app. After that I clicked on the New game option. And played a game. After that I saved that game. Then I clicked on the preferences option and then I activated show word length breakdown. After that I clicked on the dictionary option and changed the language. After that I got back to the mainscreen and started a new game and saved it. After that I clicked on preferences option and clicked on the dictionary option and then changed the language. After that went to the homescreen of the app and clicked on restore game option. But suddenly the app crashed. After that whenever I changed the language and clicked on restore game option. App always crashed.

### How to reproduce

* First you need to download the app from fdroid and then install it. After that open the app.

* Click on the new game option and then play a game. After that save it.

* Then click on preferences option. And activate the show word length breakdown option.

* After that click on the dictionary option. And change the language.

* Then get back to the mainscreen of the app. And start a new game and play it. After that save the game.

* Then click on the preferences option. After that click on the dictionary option. And change the language. Then get back to the mainscreen.

* Click on the restore game option. Suddenly the app will crash.
After that whenever you change the language and click on the restore game option. The app will crash.

https://youtu.be/4NAvpPE_aZ0

* Browser: Lexica

* Version:0.11.4

* Operating system:7.1.2

* Device model: Redmi 4

**Comment by pserwylo** [comment] 2018-06-03 21:21
Thanks for the detailed issue report (and apologies for taking a while to respond). I'll try to reproduce this some time this week and let you know if I'm successful. In the meantime, your youtube link seems to be broken.

**Comment by qoheniac** [comment] 2018-06-30 19:54
The video isn't available anymore. Beside that I cannot reproduce the crash on Android 6.0.1 using Lexica 0.11.4.

**Comment by pserwylo** [comment] 2020-09-02 12:33
Closing as this can't be reproduced. Please feel free to log another bug if it happens again in the latest version.

**Closed by pserwylo** 2020-09-02 12:33 UTC
